### ISSUE TITLE
Failure after Install.wim found on drive

### ISSUE THREAD

**Issue by hotzenwalder** [tabs-not-spaces/Intune.USB.Creator#29] opened 2021-02-17 14:20 UTC
Been trying to use the Intune USB Creator but every attempt on diferent systems and hardware fails after the message 'Install.wim found on drive E:\' with a WARING: FAILED message

Using latest veersion
![image](https://user-images.githubusercontent.com/78266646/108217636-1df89300-7134-11eb-953e-25bae2250ac8.png)

Here's the command used to built the USB on a 20Gb VHDX

Publish-ImageToUSB -winPEPath "https://githublfs.blob.core.windows.net/storage/WinPE.zip" -windowsIsoPath "M:\OSDBuilder\OSBuilds\Multilang NLUS 2009 NetFX3 19042.746\ISO\Win10 x64 2009 19042.746.iso" -getAutopilot
Cfg

![image](https://user-images.githubusercontent.com/78266646/108215471-aa558680-7131-11eb-8de3-236d4e52837c.png)

Here's the recursive directory information for the image partition

![image](https://user-images.githubusercontent.com/78266646/108215563-c1947400-7131-11eb-9fad-91f97f7090c9.png)

Here's the error

![image](https://user-images.githubusercontent.com/78266646/108215686-e38df680-7131-11eb-9f81-95fc75891354.png)

I've tried different options... 

HP EliteBook 820 G6 with a USB stick build with USB creator - Fail
Hyper-V virtual machine with two disk attached as per your example - Fail  (running on Windows Server 2016)
Hyper-V virtual machine with two disk attached as per your example - Fail  (running on Windows Server 2019)

Everything needed is on the two partitions and to rule out an error in my custom install.wim I also tried with the install.wim from the ISO's available from the Microsoft Visual Studio Download site. Used 1909 and 20H2 in UK English and both failed as well

Sort of a debug attempt

![image](https://user-images.githubusercontent.com/78266646/108216623-f81ebe80-7132-11eb-8743-61f5b459a9b8.png)

and the last part

![image](https://user-images.githubusercontent.com/78266646/108216710-108ed900-7133-11eb-8553-b957c71a7e33.png)

content of imageIndex.json

{
  "PSComputerName": "localhost",
  "RunspaceId": "cbbe17e9-506e-4205-bc0f-e657f3b36412",
  "PSShowComputerName": false,
  "ImagePath": "C:\\Users\\MARCEL~1\\AppData\\Local\\Temp\\Win10\\Images\\install.wim",
  "ImageName": "Windows 10 Enterprise",
  "ImageIndex": 1,
  "ImageDescription": "Windows 10 Enterprise",
  "ImageSize": 17346414256,
  "LogPath": "C:\\Windows\\Logs\\DISM\\dism.log",
  "ScratchDirectory": null,
  "LogLevel": "WarningsInfo"
}

Intune.USB.Creator was used on Windows Server 2016 and Windows Server 2019 both with the same results.

**Comment by tabs-not-spaces** [comment] 2021-02-18 01:04
Thanks for the detailed issue - managed to repro it and found the problem was with a failed upload of the WinPE media to Azure.
I've reuploaded and tested and can verify the issue is not reproducible now.

Please make sure that you delete the "Win10" folder in your temp directory and try running the cmdlet again - the WinPE media should be ~415MB.

Closing off the issue now, but reopen if your experience isn't the same as mine.

**Closed by tabs-not-spaces** 2021-02-18 01:04 UTC

**Comment by hotzenwalder** [comment] 2021-02-18 12:06
It's working with a VHDX which is great. I'm getting an error when writing to USB, but I must test with other hardware if this also throws the error below

![image](https://user-images.githubusercontent.com/78266646/108354633-fe23a680-71e9-11eb-8a4d-8dbb0a10374f.png)

Never had any issues with USB before and also don't needed to wipe the disk beforehand. If the issue remains I wil open a new issue
