### ISSUE TITLE
Not prompted for AutoPilot Profile

### ISSUE THREAD

**Issue by JigSawFr** [tabs-not-spaces/Intune.USB.Creator#6] opened 2020-06-27 11:50 UTC
Hello,
The script run and pass the step "Grabbing Autopilot config file from Azure.." without any window to login and select profile.
Original command was:
`Publish-ImageToUSB -winPEPath "https://githublfs.blob.core.windows.net/storage/WinPE.zip" -windowsIsoPath "C:\Users\me\Downloads\Windows10-Enterprise.iso" -getAutopilotCfg`
Any clue ?
Thank you

**Comment by tabs-not-spaces** [comment] 2020-06-29 00:07
can you verify that you've got the pre-req modules installed in the PowerShell 5.1 location?

**Comment by Ezmoshow** [comment] 2020-07-09 01:04
I ran into this issue myself a few times.. but it had worked the very first time.. subsequent times failed to grab the autoconfig file.
I went into the appdata folder where it was storing or staging the file and deleted it.  When i ran the script after deleting this, it prompted me again.

**Comment by tabs-not-spaces** [comment] 2020-07-09 03:06
Yeah that's by design - to avoid having to grab the file remotely every
time.

**Comment by tabs-not-spaces** [comment] 2020-07-14 00:45
closing issue unless someone wants to add a better solution.

**Closed by tabs-not-spaces** 2020-07-14 00:45 UTC
Labels: invalid, question
